INSERT ALL
INTO locations values ('Mumbai')
INTO locations values ('Delhi')
INTO locations values ('Bangalore')
INTO locations values ('Hyderabad')
INTO locations values ('Ahmedabad')
INTO locations values ('Chennai')
INTO locations values ('Kolkata')
INTO locations values ('Surat')
INTO locations values ('Pune')
INTO locations values ('Jaipur')
INTO locations values ('Lucknow')
INTO locations values ('Kanpur')
INTO locations values ('Nagpur')
INTO locations values ('Indore')
INTO locations values ('Thane')
INTO locations values ('Bhopal')
INTO locations values ('Visakhapatnam')
INTO locations values ('Pimpri and Chinchwad')
INTO locations values ('Patna')
INTO locations values ('Vadodara')
INTO locations values ('Ghaziabad')
INTO locations values ('Ludhiana')
INTO locations values ('Agra')
INTO locations values ('Nashik')
INTO locations values ('Faridabad')
INTO locations values ('Meerut')
INTO locations values ('Rajkot')
INTO locations values ('Kalyan and Dombivali')
INTO locations values ('Vasai Virar')
INTO locations values ('Varanasi')
INTO locations values ('Srinagar')
INTO locations values ('Aurangabad')
INTO locations values ('Dhanbad')
INTO locations values ('Amritsar')
INTO locations values ('Navi Mumbai')
INTO locations values ('Allahabad')
INTO locations values ('Ranchi')
INTO locations values ('Haora')
INTO locations values ('Coimbatore')
INTO locations values ('Jabalpur')
INTO locations values ('Gwalior')
INTO locations values ('Vijayawada')
INTO locations values ('Jodhpur')
INTO locations values ('Madurai')
INTO locations values ('Raipur')
INTO locations values ('Kota')
INTO locations values ('Guwahati')
INTO locations values ('Chandigarh')
INTO locations values ('Solapur')
INTO locations values ('Hubli and Dharwad')
INTO locations values ('Bareilly')
INTO locations values ('Moradabad')
INTO locations values ('Mysore')
INTO locations values ('Gurgaon')
INTO locations values ('Aligarh')
INTO locations values ('Jalandhar')
INTO locations values ('Tiruchirappalli')
INTO locations values ('Bhubaneswar')
INTO locations values ('Salem')
INTO locations values ('Mira and Bhayander')
INTO locations values ('Thiruvananthapuram')
INTO locations values ('Bhiwandi')
INTO locations values ('Saharanpur')
INTO locations values ('Gorakhpur')
INTO locations values ('Guntur')
INTO locations values ('Bikaner')
INTO locations values ('Amravati')
INTO locations values ('Noida')
INTO locations values ('Jamshedpur')
INTO locations values ('Bhilai Nagar')
INTO locations values ('Warangal')
INTO locations values ('Cuttack')
INTO locations values ('Firozabad')
INTO locations values ('Kochi')
INTO locations values ('Bhavnagar')
INTO locations values ('Dehradun')
INTO locations values ('Durgapur')
INTO locations values ('Asansol')
INTO locations values ('Nanded')
INTO locations values ('Kolapur')
INTO locations values ('Ajmer')
INTO locations values ('Gulbarga')
INTO locations values ('Jamnagar')
INTO locations values ('Ujjain')
INTO locations values ('Loni')
INTO locations values ('Siliguri')
INTO locations values ('Jhansi')
INTO locations values ('Ulhasnagar')
INTO locations values ('Nellore')
INTO locations values ('Jammu')
INTO locations values ('Sangli Miraj Kupwad')
INTO locations values ('Belgaum')
INTO locations values ('Mangalore')
INTO locations values ('Ambattur')
INTO locations values ('Tirunelveli')
INTO locations values ('Malegoan')
INTO locations values ('Gaya')
INTO locations values ('Jalgaon')
INTO locations values ('Udaipur')
INTO locations values ('Maheshtala')
SELECT 1 FROM DUAL;

insert all into customer (customer_id,fname,lname,phone,email,login_id,passwd) values (
'ABC123','admin','admin',1234567890,'admin@123.com','admin1234','admin@123'
) select 1 from dual;

-- TODO: Enter dummy data for employee, booking, car, carrental, carpooling